# SPDX-License-Identifier: MIT
"""Case definitions for the Maxent regression suite.

Each case is a dict with:
  name      unique case name (also the reference file name)
  set       'full' (shipped examples), 'fast' (examples, reduced size),
            'targeted' (synthetic inputs), 'cli' (command-line snapshots),
            'kk' (the kk utility), or 'legendre_convert'
  program   'maxent' (default), 'kk', or 'legendre_convert'
  inputs    directory with the input files, relative to the repository root
  param     parameter file inside `inputs` (None for 'cli' cases)
  args      extra command-line arguments (overrides or CLI flags)
  covers    short description of what the case exercises
  flags     known issues (see ALPS3_MIGRATION_PLAN.md, section 1.6) whose
            current behavior the reference records
  expect    expected run status: 'ok', or 'exception' when maxent is expected
            to report an error
"""

EXAMPLES = [
    # name,                 directory,              parameter file,   covers
    ("u0_frequency",        "examples/U0",          "in.param",       "fermionic, frequency, PH, text data"),
    ("u0_time",             "examples/U0",          "in_tau.param",   "fermionic, time, TAU_i in parameter file"),
    ("u2_frequency",        "examples/U2",          "frequency.param", "fermionic, frequency, non-PH, NORM"),
    ("u2_time",             "examples/U2",          "time.param",     "fermionic, time, non-PH"),
    ("u2_self",             "examples/U2",          "self.param",     "self-energy (SELF), frequency, non-PH"),
    ("bosonic",             "examples/Bosonic",     "bosonic.param",  "bosonic, frequency, non-PH"),
    ("bosonic_ph",          "examples/Bosonic",     "bosonic_ph.param", "bosonic, frequency, PH"),
    ("legendre",            "examples/Legendre",    "in.param",       "fermionic, Legendre, quadratic grid"),
    ("self_u1",             "examples/Self Energy/U1",  "in.param",   "self-energy, quadratic grid, OMEGA_MAX"),
    ("self_u10",            "examples/Self Energy/U10", "in.param",   "self-energy, quadratic grid, NORM"),
    ("self_u10_green",      "examples/Self Energy/U10", "green.param", "double Gaussian default model, quadratic grid"),
]

FAST_ARGS = ["--NFREQ=200", "--N_ALPHA=20"]
FAST_ARGS_LEGENDRE = ["--NFREQ=500", "--N_ALPHA=20"]

# Targeted cases: inputs are generated by make_inputs.py into inputs/<name>/.
# The parameter file is always 'case.param'.
TARGETED = [
    ("t_cov_text",            "covariance matrix from text file, time fermionic", []),
    ("t_cov_hdf5",            "DATA_IN_HDF5 with /Covariance, frequency PH", []),
    ("t_hdf5_errors",         "DATA_IN_HDF5 with /Error, frequency non-PH", []),
    ("t_param_xi",            "data as X_i/SIGMA_i in parameter file, frequency PH", []),
    ("t_param_taui",          "X_i/SIGMA_i/TAU_i in parameter file, time fermionic", []),
    ("t_kernel_tzero",        "T=0 kernel, OMEGA_MIN=0", []),
    ("t_kernel_time_bosonic", "time bosonic kernel, OMEGA_MIN=0", ["B7 (fixed; K(i,0)=T assumes the grid starts at 0)"]),
    ("t_kernel_anomalous_ph", "anomalous kernel, frequency PH", []),
    ("t_kernel_anomalous_nonph", "anomalous kernel, frequency non-PH", []),
    ("t_kernel_legendre_bosonic", "Legendre bosonic kernel", ["B17 (Legendre bosonic uses the fermionic integrand)"]),
    ("t_model_flat",          "default model: flat", []),
    ("t_model_gaussian",      "default model: gaussian", []),
    ("t_model_shifted_gaussian", "default model: shifted gaussian", []),
    ("t_model_double_gaussian", "default model: double gaussian", []),
    ("t_model_two_gaussians", "default model: two gaussians", []),
    ("t_model_general_double_gaussian", "default model: general double gaussian", []),
    ("t_model_lorentzian",    "default model: lorentzian", []),
    ("t_model_shifted_lorentzian", "default model: shifted lorentzian", []),
    ("t_model_double_lorentzian", "default model: double lorentzian", []),
    ("t_model_two_lorentzians", "default model: two lorentzians", []),
    ("t_model_linear_rise_exp_decay", "default model: linear rise exp decay (T=0 kernel, OMEGA_MIN=0)", []),
    ("t_model_quadratic_rise_exp_decay", "default model: quadratic rise exp decay (T=0 kernel, OMEGA_MIN=0)", []),
    ("t_model_tabulated",     "default model: tabulated file", []),
    ("t_grid_lorentzian",     "grid: lorentzian", []),
    ("t_grid_half_lorentzian", "grid: half lorentzian", ["B16 (help text says 'half-lorentzian')"]),
    ("t_grid_quadratic",      "grid: quadratic", []),
    ("t_grid_log",            "grid: log", []),
    ("t_grid_linear",         "grid: linear", []),
    ("t_model_runs",          "MODEL_RUNS=2 (flat, gaussian): per-model outputs and varspec", []),
]

CLI = [
    ("cli_help",         ["--help"],        "--help output"),
    ("cli_help_models",  ["--help.models"], "--help.models output"),
    ("cli_help_grids",   ["--help.grids"],  "--help.grids output"),
    ("cli_missing_beta", None,              "error output when BETA is missing (B1: exit code is 0)"),
]


# kk utility: inputs in inputs/<name>/input.dat, generated by make_inputs.py from
# spectra in the maxent references (Im parts) or analytically (Re part).
KK = [
    ("kk_imag_to_real_green", "--imag_to_real", "Im G(omega) = -pi A(omega) of u0_frequency (average spectrum)"),
    ("kk_imag_to_real_self",  "--imag_to_real", "Im Sigma(omega) of self_u1 (average spectrum)"),
    ("kk_real_to_imag",       "--real_to_imag", "Re G(omega) of a unit Gaussian spectrum (Dawson function)"),
]


LEGENDRE_CONVERT = [
    dict(name="legendre_convert_transform", set="legendre_convert",
         program="legendre_convert",
         inputs="test/regression/inputs/legendre_convert_transform",
         param=None,
         args=["--beta=5", "--input_gtau_file=input.dat", "--output_gl_file=Gl.dat",
               "--tail1=1", "--tail2=0", "--lmax=12", "--maxit=10", "--backcontinue",
               "--plot_convergence=12", "--maxn=3", "--noerr"],
         covers="legendre_convert: transform, tails, back-continuation, and Matsubara convergence",
         flags=[], expect="ok"),
]


def all_cases():
    cases = []
    for name, directory, param, covers in EXAMPLES:
        cases.append(dict(name=name, set="full", inputs=directory, param=param,
                          args=[], covers=covers, flags=[], expect="ok"))
        fast_args = FAST_ARGS_LEGENDRE if name == "legendre" else FAST_ARGS
        cases.append(dict(name=name + "_fast", set="fast", inputs=directory, param=param,
                          args=list(fast_args), covers=covers + " (reduced size)", flags=[],
                          expect="ok"))
    for name, covers, flags in TARGETED:
        cases.append(dict(name=name, set="targeted", inputs="test/regression/inputs/" + name,
                          param="case.param", args=[], covers=covers, flags=list(flags),
                          expect="ok"))
    for name, args, covers in CLI:
        if args is None:
            cases.append(dict(name=name, set="cli", inputs="test/regression/inputs/" + name,
                              param="case.param", args=[], covers=covers, flags=["B1"],
                              expect="exception"))
        else:
            cases.append(dict(name=name, set="cli", inputs=None, param=None,
                              args=args, covers=covers,
                              flags=["B16"] if name == "cli_help_grids" else [],
                              expect="ok"))
    for name, direction, covers in KK:
        cases.append(dict(name=name, set="kk", program="kk", inputs="test/regression/inputs/" + name,
                          param=None, args=["--input_file=input.dat", "--output_file=output.dat", direction],
                          covers="kk: " + covers, flags=[], expect="ok"))
    cases.extend(LEGENDRE_CONVERT)
    for c in cases:
        c.setdefault("program", "maxent")
    return cases
