#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Write MANIFEST.md from the references, the case definitions and the tolerances.

    python3 test/regression/manifest.py      # rewrites test/regression/MANIFEST.md

Run it after regenerating references so the manifest always matches them.
"""

import json
import sys
from pathlib import Path

import h5py

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from cases import all_cases  # noqa: E402

SET_TITLES = [
    ("fast", "Fast set (examples, reduced size)"),
    ("targeted", "Targeted cases (synthetic inputs, see make_inputs.py)"),
    ("cli", "Command-line snapshots"),
    ("full", "Full set (examples as shipped, opt-in)"),
    ("kk", "kk utility"),
    ("components", "Components"),
]


def count_datasets(h5):
    n = [0]

    def visit(name, obj):
        if isinstance(obj, h5py.Dataset) and name.split("/")[0] in ("files", "cli") \
                or name.startswith("log/scalars/"):
            n[0] += 1

    h5.visititems(visit)
    return n[0]


def main():
    ref_dir = HERE / "reference"
    cases = {c["name"]: c for c in all_cases()}
    cases["components"] = dict(name="components", set="components", inputs="components/dump_components.cpp",
                               covers="kernel matrices (11 reachable kernel types), grids (5 types, "
                                      "odd/even), default models (13), singular values", flags=[],
                               expect="ok")
    lines = ["# Regression suite manifest", "",
             "Generated by `manifest.py` from `reference/`, `cases.py` and `tolerances.json`. "
             "Do not edit by hand.", ""]
    total = 0
    for set_name, title in SET_TITLES:
        names = sorted(n for n, c in cases.items() if c["set"] == set_name)
        lines += [f"## {title}", "", "| Case | Covers | Inputs | Datasets | Runtime | Flags |",
                  "|---|---|---|---|---|---|"]
        for name in names:
            c = cases[name]
            path = ref_dir / f"{name}.h5"
            if path.exists():
                with h5py.File(path, "r") as h5:
                    nd = count_datasets(h5)
                    rt = f"{h5.attrs['runtime_seconds']:.1f} s"
            else:
                nd, rt = 0, "missing"
            total += nd
            flags = ", ".join(c["flags"])
            if c.get("expect", "ok") != "ok":
                flags = (flags + "; " if flags else "") + f"expects {c['expect']}"
            inputs = f"`{c['inputs']}`" if c.get("inputs") else "none"
            args = " ".join(c.get("args", []))
            covers = c["covers"] + (f" (`{args}`)" if args else "")
            lines.append(f"| `{name}` | {covers} | {inputs} | {nd} | {rt} | {flags} |")
        lines.append("")
    rules = json.loads((HERE / "tolerances.json").read_text())
    lines += ["## Tolerances", "", rules.get("description", ""), "",
              "| Pattern (case:dataset) | atol | rtol | Why |", "|---|---|---|---|"]
    for r in rules["rules"]:
        lines.append(f"| `{r['pattern']}` | {r['atol']:g} | {r['rtol']:g} | {r.get('why', '')} |")
    lines += ["", f"Total compared datasets: {total} in {len(cases)} cases.", "",
              "## Known limitations", "",
              "* The Legendre example is extremely ill-conditioned (minimal chi2 ~ 1e-17): rounding-level "
              "differences in the kernel change its alpha probabilities and Ng by up to 3e-3 and 3e-2 "
              "between compilers, so its end-to-end tolerances are loose. Kernel changes are caught by the "
              "Legendre kernel matrices in `components.h5`, compared at 1e-14. (Check: replacing GSL by "
              "Boost Gauss-Kronrod reproduces the Legendre kernels to 2e-16.)",
              "* `-O0` builds take more than 30 minutes for the full `legendre` case.",
              "* `*.spex.dat`, `*.fits.dat` and `*.booterr.dat` are not compared (see README.md).", ""]
    (HERE / "MANIFEST.md").write_text("\n".join(lines))
    print(f"wrote MANIFEST.md: {len(cases)} cases, {total} datasets")


if __name__ == "__main__":
    main()
